name: Bug Report
description: Report an issue to make ViRe better
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # Bug report
        *Thanks for taking the time to fill out this bug report and helping improve ViRe!*
        Please try to fill out all fields to the best of your ability.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Clearly and concisely write up the problem.
      placeholder: Enter your description here.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Hover the '...' menu option
        2. Click '....' button
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
      placeholder: Type here.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Upload your screenshots here. You can paste them or click on "Attach files".
    validations:
      required: false
  - type: textarea
    id: troubleshooting
    attributes:
      label: Troubleshooting
      description: Which steps, if any, did you take to troubleshoot?
      placeholder: |
        1. Tried it on version '...'
        2. Changed the '...' SteamVR setting
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version(s)
      description: Grab the version from the zip name. You can list several
      placeholder: v0.12.1A
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      multiple: true
      options:
        - Windows
        - Linux
    validations:
      required: true
  - type: input
    id: headset
    attributes:
      label: VR headset
      description: Which headset did you use? You can specify multiple
      placeholder: HTC Vive
    validations:
      required: true
  - type: checkboxes
    id: discord
    attributes:
      label: Did you reach out to us or see this issue reported on Discord?
      description: We want to know so that we can match up your report(s) there
      options:
        - label: Reported on Discord
          required: false
  - type: dropdown
    id: help
    attributes:
      label: Can you help build a fix?
      description: |
        In most cases, especially when the issue is hardware-specific, we could really use real-time help in debugging or testing fixes.
        If you agree to help, you'll need to run the project in the Unity Editor (version in the `README.md`) and we might ask you to hop into a call for live testing.
      multiple: false
      options:
        - No, I'm only able to answer questions about my setup or the issue
        - Yes, I'm able to work with you using the Unity editor to fix the issue
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: Is there anything else we should know?
    validations:
      required: false
